services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  
  # php
  php8:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
       - ./projects/:/var/www/html/
  # mysql
  # redis