services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  
  # php
  php8:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
       - ./projects/:/var/www/html/
  # mysql

  mysql:
    image: mysql:8.0
    
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: learn_docker
      

  # redis



volumes:
  mysqldata: